### ISSUE TITLE
Snapshoty pojmů vrácené TermIt API neobsahují některé atributy

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit#161]
Endpoint se snapshotem pojmu by měl vracet v elementu properties tyto atributy:
http://onto.fel.cvut.cz/ontologies/slovnik/slovník-datového-modelu-dtm/pojem/je-reálným-objektem
http://purl.org/dc/terms/references
http://www.w3.org/2004/02/skos/core#notation
http://www.w3.org/2004/02/skos/core#example

Tady příklad pojmu v aktuálních datech a ve verzi, kdy datově by měly být totožné:

- https://termit.fel.cvut.cz/service/ipr/termit/rest/public/terms/cyklostezka?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/dtm/pojem

- https://termit.fel.cvut.cz/service/ipr/termit/rest/public/terms/cyklostezka/versions?n[…]C3%ADk.gov.cz/datov%C3%BD/dtm/pojem&at=2022-07-04T08:50:30Z

**Comment by ledsoft** [comment]
Dalším případem chybějících atributů jsou inferované `skos:exactMatch`, `skos:related`, `skos:relatedMatch` vztahy.
