### ISSUE TITLE
Test failure while running on Windows

### ISSUE THREAD

**Issue by lukaskabc** [kbss-cvut/termit#275]
When run on Windows, the test fails.

# System information
Windows 10 Pro 22H2
Oracle OpenJDK version 17.0.1 (build 17.0.1+12-LTS-39)
Active Maven profiles: standalone,graphdb

# Test output
```
[ERROR] Failures: 
[ERROR]   HtmlTermOccurrenceResolverTest.findTermOccurrencesSetsFoundOccurrencesAsApprovedWhenCorrespondingExistingOccurrenceWasApproved:193 
Expected: not a collection containing "http://onto.fel.cvut.cz/ontologies/application/termit/pojem/navržený-výskyt-termu"
     but: was <[http://onto.fel.cvut.cz/ontologies/application/termit/pojem/navržený-výskyt-termu]>
[INFO] 
[ERROR] Tests run: 1407, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```

[Line 193 permalink](https://github.com/kbss-cvut/termit/blob/cf5e5f35f219a53cda29ce178e44e72b2474c17e/src/test/java/cz/cvut/kbss/termit/service/document/html/HtmlTermOccurrenceResolverTest.java#L193)

**Comment by ledsoft** [comment]
I am unable to reproduce it (Windows 11, JDK Temurin 21). Does the failure happen occasionally, or every time?

**Comment by lukaskabc** [comment]
After [enabling the test for Windows](https://github.com/kbss-cvut/termit/blob/master/src/test/java/cz/cvut/kbss/termit/service/document/html/HtmlTermOccurrenceResolverTest.java#L183) and rerunning it on Windows 11, JDK Temurin 21 with  
`clean test -Dtest=HtmlTermOccurrenceResolverTest` the test still fails.
So far, it has failed every time.

**Comment by ledsoft** [comment]
Yeah, you are right. I am an idiot, I forgot the test was disabled on Windows... Now I can reproduce it as well.

**Comment by ledsoft** [comment]
Of course it was a linefeed issue. Added configuration to use consistent line endings for files. Hopefully that should resolve the problem.
